<?php
declare(strict_types=1);

return [
  'metrics' => [
    ['key' => 'valuta', 'label_key' => 'valuta', 'fmt' => 'text'],
    ['key' => 'reddito_medio', 'label_key' => 'reddito_medio', 'unit_key' => 'unit_eur_year', 'fmt' => 'eur0'],
    ['key' => 'debt_gdp', 'label_key' => 'debt_gdp', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'politiche_economiche', 'label_key' => 'politiche_economiche', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'protezione_sociale', 'label_key' => 'protezione_sociale', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'sanita', 'label_key' => 'sanita', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'interessi', 'label_key' => 'interessi', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'pubblica_amministrazione', 'label_key' => 'pubblica_amministrazione', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'istruzione_ricerca', 'label_key' => 'istruzione_ricerca', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'difesa', 'label_key' => 'difesa', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'bilancio_ue', 'label_key' => 'bilancio_ue', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'infrastrutture', 'label_key' => 'infrastrutture', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'sicurezza', 'label_key' => 'sicurezza', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'protezione_ambientale', 'label_key' => 'protezione_ambientale', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'giustizia', 'label_key' => 'giustizia', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'cultura', 'label_key' => 'cultura', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
    ['key' => 'altro', 'label_key' => 'altro', 'unit_key' => 'unit_pct', 'fmt' => 'pct1'],
  ],
  'countries' => [
    'IT' => [
      'name_it' => 'Italia',
      'name_en' => 'Italy',
      'flag_path' => '/imm/flags/it.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 31856,
        'debt_gdp' => 137.8,
        'politiche_economiche' => 20.9,
        'protezione_sociale' => 20.6,
        'pubblica_amministrazione' => 8.6,
        'sanita' => 10.1,
        'interessi' => 11.6,
        'istruzione_ricerca' => 7.9,
        'difesa' => 3.4,
        'bilancio_ue' => 2.5,
        'infrastrutture' => 2.5,
        'sicurezza' => 2.5,
        'protezione_ambientale' => 2.4,
        'giustizia' => 1.3,
        'cultura' => 0.6,
        'altro' => 5.1,
      ],
    ],
    'FR' => [
      'name_it' => 'Francia',
      'name_en' => 'France',
      'flag_path' => '/imm/flags/fr.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 43356,
        'debt_gdp' => 117.7,
        'politiche_economiche' => 29.0,
        'protezione_sociale' => 9.6,
        'pubblica_amministrazione' => 7.4,
        'sanita' => 0.2,
        'interessi' => 8.2,
        'istruzione_ricerca' => 17.5,
        'difesa' => 8.8,
        'bilancio_ue' => 3.4,
        'infrastrutture' => 1.5,
        'sicurezza' => 3.7,
        'protezione_ambientale' => 2.9,
        'giustizia' => 1.9,
        'cultura' => 1.2,
        'altro' => 4.7,
      ],
    ],
    'DE' => [
      'name_it' => 'Germania',
      'name_en' => 'Germany',
      'flag_path' => '/imm/flags/de.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 51000,
        'debt_gdp' => 63.0,
        'politiche_economiche' => 6.2,
        'protezione_sociale' => 40.5,
        'pubblica_amministrazione' => 8.9,
        'sanita' => 3.9,
        'interessi' => 5.6,
        'istruzione_ricerca' => 5.8,
        'difesa' => 13.0,
        'bilancio_ue' => 6.3,
        'infrastrutture' => 5.8,
        'sicurezza' => 1.6,
        'protezione_ambientale' => 0.5,
        'giustizia' => 0.2,
        'cultura' => 0.1,
        'altro' => 1.6,
      ],
    ],
    'ES' => [
      'name_it' => 'Spagna',
      'name_en' => 'Spain',
      'flag_path' => '/imm/flags/es.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 23349,
        'debt_gdp' => 103.2,
        'politiche_economiche' => 3.4,
        'protezione_sociale' => 56.0,
        'pubblica_amministrazione' => 17.4,
        'sanita' => 1.2,
        'interessi' => 6.9,
        'istruzione_ricerca' => 2.8,
        'difesa' => 2.7,
        'bilancio_ue' => 3.9,
        'infrastrutture' => 0.7,
        'sicurezza' => 2.3,
        'protezione_ambientale' => 1.8,
        'giustizia' => 0.5,
        'cultura' => 0.3,
        'altro' => 0.1,
      ],
    ],
    'BE' => [
      'name_it' => 'Belgio',
      'name_en' => 'Belgium',
      'flag_path' => '/imm/flags/be.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 58000,
        'debt_gdp' => 107.1,
        'politiche_economiche' => 6.7,
        'protezione_sociale' => 37.7,
        'pubblica_amministrazione' => 7.1,
        'sanita' => 14.8,
        'interessi' => 4.1,
        'istruzione_ricerca' => 11.7,
        'difesa' => 2.4,
        'bilancio_ue' => 2.0,
        'infrastrutture' => 5.2,
        'sicurezza' => 2.7,
        'protezione_ambientale' => 2.1,
        'giustizia' => 0.4,
        'cultura' => 2.3,
        'altro' => 0.8,
      ],
    ],
    'LU' => [
      'name_it' => 'Lussemburgo',
      'name_en' => 'Luxembourg',
      'flag_path' => '/imm/flags/lu.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 75919,
        'debt_gdp' => 27.9,
        'politiche_economiche' => 5.6,
        'protezione_sociale' => 24.3,
        'pubblica_amministrazione' => 6.8,
        'sanita' => 8.8,
        'interessi' => 1.0,
        'istruzione_ricerca' => 17.2,
        'difesa' => 4.7,
        'bilancio_ue' => 1.6,
        'infrastrutture' => 10.8,
        'sicurezza' => 9.7,
        'protezione_ambientale' => 1.6,
        'giustizia' => 1.2,
        'cultura' => 1.2,
        'altro' => 5.5,
      ],
    ],
    'NL' => [
      'name_it' => 'Olanda',
      'name_en' => 'Netherlands',
      'flag_path' => '/imm/flags/nl.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 54900,
        'debt_gdp' => 42.4,
        'politiche_economiche' => 6.1,
        'protezione_sociale' => 23.8,
        'pubblica_amministrazione' => 13.5,
        'sanita' => 24.2,
        'interessi' => 1.8,
        'istruzione_ricerca' => 11.7,
        'difesa' => 4.7,
        'bilancio_ue' => 2.3,
        'infrastrutture' => 3.9,
        'sicurezza' => 2.4,
        'protezione_ambientale' => 1.1,
        'giustizia' => 1.4,
        'cultura' => 0.7,
        'altro' => 2.4,
      ],
    ],
    'AT' => [
      'name_it' => 'Austria',
      'name_en' => 'Austria',
      'flag_path' => '/imm/flags/at.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 55678,
        'debt_gdp' => 83.7,
        'politiche_economiche' => 7.6,
        'protezione_sociale' => 45.9,
        'pubblica_amministrazione' => 2.5,
        'sanita' => 2.2,
        'interessi' => 6.6,
        'istruzione_ricerca' => 15.9,
        'difesa' => 3.5,
        'bilancio_ue' => 2.5,
        'infrastrutture' => 4.8,
        'sicurezza' => 3.8,
        'protezione_ambientale' => 1.7,
        'giustizia' => 1.9,
        'cultura' => 0.9,
        'altro' => 0.2,
      ],
    ],
    'HR' => [
      'name_it' => 'Croazia',
      'name_en' => 'Croatia',
      'flag_path' => '/imm/flags/hr.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 25000,
        'debt_gdp' => 57.2,
        'politiche_economiche' => 11.6,
        'protezione_sociale' => 32.5,
        'pubblica_amministrazione' => 5.3,
        'sanita' => 12.9,
        'interessi' => 2.9,
        'istruzione_ricerca' => 7.4,
        'difesa' => 4.1,
        'bilancio_ue' => 2.1,
        'infrastrutture' => 6.8,
        'sicurezza' => 4.6,
        'protezione_ambientale' => 0.6,
        'giustizia' => 1.9,
        'cultura' => 3.1,
        'altro' => 4.2,
      ],
    ],
    'PL' => [
      'name_it' => 'Polonia',
      'name_en' => 'Poland',
      'flag_path' => '/imm/flags/pl.png',
      'metrics' => [
        'valuta' => 'PLN',
        'reddito_medio' => 25675,
        'debt_gdp' => 58.1,
        'politiche_economiche' => 4.6,
        'protezione_sociale' => 46.2,
        'pubblica_amministrazione' => 14.2,
        'sanita' => 2.4,
        'interessi' => 5.7,
        'istruzione_ricerca' => 9.5,
        'difesa' => 7.4,
        'bilancio_ue' => 1.4,
        'infrastrutture' => 2.3,
        'sicurezza' => 2.2,
        'protezione_ambientale' => 1.2,
        'giustizia' => 1.9,
        'cultura' => 0.8,
        'altro' => 0.2,
      ],
    ],
    'PT' => [
      'name_it' => 'Portogallo',
      'name_en' => 'Portugal',
      'flag_path' => '/imm/flags/pt.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 23058,
        'debt_gdp' => 97.6,
        'politiche_economiche' => 6.1,
        'protezione_sociale' => 36.7,
        'pubblica_amministrazione' => 3.9,
        'sanita' => 17.2,
        'interessi' => 2.7,
        'istruzione_ricerca' => 13.1,
        'difesa' => 3.0,
        'bilancio_ue' => 2.0,
        'infrastrutture' => 7.1,
        'sicurezza' => 2.0,
        'protezione_ambientale' => 1.5,
        'giustizia' => 1.3,
        'cultura' => 3.2,
        'altro' => 0.2,
      ],
    ],
    'SI' => [
      'name_it' => 'Slovenia',
      'name_en' => 'Slovenia',
      'flag_path' => '/imm/flags/si.png',
      'metrics' => [
        'valuta' => 'EUR',
        'reddito_medio' => 30432,
        'debt_gdp' => 67.6,
        'politiche_economiche' => 6.1,
        'protezione_sociale' => 36.7,
        'pubblica_amministrazione' => 3.9,
        'sanita' => 17.2,
        'interessi' => 2.7,
        'istruzione_ricerca' => 13.1,
        'difesa' => 3.0,
        'bilancio_ue' => 2.0,
        'infrastrutture' => 7.1,
        'sicurezza' => 2.0,
        'protezione_ambientale' => 1.5,
        'giustizia' => 1.3,
        'cultura' => 3.2,
        'altro' => 0.2,
      ],
    ],
  ],
];
